# Auto-generated by IDE. All changes by user will be lost!
# Created at 08/01/13 11:27 AM

BASEDIR = $$_PRO_FILE_PWD_

INCLUDEPATH +=  \
    $$BASEDIR/src

SOURCES +=  \
    $$BASEDIR/src/ActiveFrame.cpp \
    $$BASEDIR/src/UITest.cpp \
    $$BASEDIR/src/main.cpp

HEADERS +=  \
    $$BASEDIR/src/ActiveFrame.h \
    $$BASEDIR/src/UITest.hpp

lupdate_inclusion {
    SOURCES += \
        $$BASEDIR/../assets/*.qml
}

TRANSLATIONS = \
    $${TARGET}.ts

